### PR TITLE
Minor typographical fixes

### PR DESCRIPTION
**Pull request by alexwlchan**
* The usual formatting for eleven-digit UK telephone numbers is to
  include a space between the area code and the six-digit subscriber
  code.  (I work in telecoms. =P)
* The en dash is preferred for ranges in some style guides; depends
  on which you're using.  This is the double dash in LaTeX.
  Ref: https://en.wikipedia.org/wiki/Dash#En_dash
* Improve the rendering of "C++".

---

Because I am me. Feel free to accept or ignore as you see fit. The one bit I’m proud of is the C++ tweaks, here’s a comparison of the old/new:

screen shot 2016-09-24 at 19 39 51

The "+" no longer looks out of place in the rest of the document.

*skulks back to feeling inadequate from reading your CV*

### CODE REVIEW

**Comment by oliviaguest** [comment]
Are you serious?! This is so awesome. **THIS** is what friends are for! ❤️

**Comment by lpar** [comment]
I'd suggest either putting the phone numbers in UK format, or in international format, and not a strange mixture of the two.
See http://meta.ath0.com/2010/08/11/phone-numbers/

**Comment by alexwlchan** [comment]
> I'd suggest either putting the phone numbers in UK format, or in international format, and not a strange mixture of the two.

Yeah, I should probably have noticed that didn’t look quite right. Addressed in #3.

**Comment by oliviaguest** [comment]
I'm so unbelievably thankful, you two are great! Almost restoring my belief in the interwebs. 💙

**Pull request merged**
